apiVersion: v1
kind: Service
metadata:
  name: slips-data-svc
  labels:
    app: slips-data-svc
    version: stable
  namespace: kb-service
spec:
  selector:
    app: slips-data-svc
    version: stable
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 5000
      nodePort: 30699
  type: NodePort