apiVersion: apps/v1
kind: Deployment
metadata:
  name: slips-data-svc
  namespace: kb-service
  labels:
    app: slips-data-svc
    version: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slips-data-svc
      version: stable
  template:
    metadata:
      labels:
        app: slips-data-svc
        version: stable
    spec:
     containers:
       volumeMounts:
       - name: slips-svc-config
         mountPath: /home/slips/data/config
       - name: config
         mountPath: /home/slips/data/config
       name: slips-data-svc
       image: registry.pintechs.com/slips/slips-data-svc:v0.6
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 5000